package com.eugenefe.entity;
// Generated Mar 16, 2016 4:59:04 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * OdsKrxOptionPriceAuto generated by hbm2java
 */
@Entity
@Table(name = "ods_krx_option_price_auto", catalog = "eugenefe")
public class OdsKrxOptionPriceAuto implements java.io.Serializable {

	private Integer seqId;
	private String workDt;
	private String isuCd;
	private String opnPr;
	private String hgPr;
	private String lwPr;
	private String endPr;
	private String endRt;
	private String TDdTrVl;
	private String TDdTrAmt;
	private String opnIntCtrVl;
	private String impVola;
	private String setlmult;

	public OdsKrxOptionPriceAuto() {
	}

	public OdsKrxOptionPriceAuto(String workDt, String isuCd, String opnPr, String hgPr, String lwPr, String endPr,
			String endRt, String TDdTrVl, String TDdTrAmt, String opnIntCtrVl, String impVola, String setlmult) {
		this.workDt = workDt;
		this.isuCd = isuCd;
		this.opnPr = opnPr;
		this.hgPr = hgPr;
		this.lwPr = lwPr;
		this.endPr = endPr;
		this.endRt = endRt;
		this.TDdTrVl = TDdTrVl;
		this.TDdTrAmt = TDdTrAmt;
		this.opnIntCtrVl = opnIntCtrVl;
		this.impVola = impVola;
		this.setlmult = setlmult;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@JsonIgnore
	@Column(name = "SEQ_ID", unique = true, nullable = false)
	public Integer getSeqId() {
		return this.seqId;
	}

	public void setSeqId(Integer seqId) {
		this.seqId = seqId;
	}

	@Column(name = "WORK_DT", length = 8)
	public String getWorkDt() {
		return this.workDt;
	}

	public void setWorkDt(String workDt) {
		this.workDt = workDt;
	}

	@Column(name = "ISU_CD", length = 20)
	public String getIsuCd() {
		return this.isuCd;
	}

	public void setIsuCd(String isuCd) {
		this.isuCd = isuCd;
	}

	@Column(name = "OPN_PR", length = 20)
	public String getOpnPr() {
		return this.opnPr;
	}

	public void setOpnPr(String opnPr) {
		this.opnPr = opnPr;
	}

	@Column(name = "HG_PR", length = 20)
	public String getHgPr() {
		return this.hgPr;
	}

	public void setHgPr(String hgPr) {
		this.hgPr = hgPr;
	}

	@Column(name = "LW_PR", length = 20)
	public String getLwPr() {
		return this.lwPr;
	}

	public void setLwPr(String lwPr) {
		this.lwPr = lwPr;
	}

	@Column(name = "END_PR", length = 20)
	public String getEndPr() {
		return this.endPr;
	}

	public void setEndPr(String endPr) {
		this.endPr = endPr;
	}

	@Column(name = "END_RT", length = 20)
	public String getEndRt() {
		return this.endRt;
	}

	public void setEndRt(String endRt) {
		this.endRt = endRt;
	}
	
	@JsonGetter("t_dd_tr_vl")
	@Column(name = "T_DD_TR_VL", length = 20)
	public String getTDdTrVl() {
		return this.TDdTrVl;
	}

	public void setTDdTrVl(String TDdTrVl) {
		this.TDdTrVl = TDdTrVl;
	}

	@JsonGetter("t_dd_tr_amt")
	@Column(name = "T_DD_TR_AMT", length = 20)
	public String getTDdTrAmt() {
		return this.TDdTrAmt;
	}

	public void setTDdTrAmt(String TDdTrAmt) {
		this.TDdTrAmt = TDdTrAmt;
	}

	@Column(name = "OPN_INT_CTR_VL", length = 20)
	public String getOpnIntCtrVl() {
		return this.opnIntCtrVl;
	}

	public void setOpnIntCtrVl(String opnIntCtrVl) {
		this.opnIntCtrVl = opnIntCtrVl;
	}

	@Column(name = "IMP_VOLA", length = 20)
	public String getImpVola() {
		return this.impVola;
	}

	public void setImpVola(String impVola) {
		this.impVola = impVola;
	}

	@Column(name = "SETLMULT", length = 20)
	public String getSetlmult() {
		return this.setlmult;
	}

	public void setSetlmult(String setlmult) {
		this.setlmult = setlmult;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((TDdTrAmt == null) ? 0 : TDdTrAmt.hashCode());
		result = prime * result + ((TDdTrVl == null) ? 0 : TDdTrVl.hashCode());
		result = prime * result + ((endPr == null) ? 0 : endPr.hashCode());
		result = prime * result + ((endRt == null) ? 0 : endRt.hashCode());
		result = prime * result + ((hgPr == null) ? 0 : hgPr.hashCode());
		result = prime * result + ((impVola == null) ? 0 : impVola.hashCode());
		result = prime * result + ((isuCd == null) ? 0 : isuCd.hashCode());
		result = prime * result + ((lwPr == null) ? 0 : lwPr.hashCode());
		result = prime * result + ((opnIntCtrVl == null) ? 0 : opnIntCtrVl.hashCode());
		result = prime * result + ((opnPr == null) ? 0 : opnPr.hashCode());
		result = prime * result + ((seqId == null) ? 0 : seqId.hashCode());
		result = prime * result + ((setlmult == null) ? 0 : setlmult.hashCode());
		result = prime * result + ((workDt == null) ? 0 : workDt.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OdsKrxOptionPriceAuto other = (OdsKrxOptionPriceAuto) obj;
		if(isuCd.equals(other.isuCd) && workDt.equals(other.workDt)){
			return true;
		}
		return false;
	}
	
	

}
