package com.eugenefe.entity;
// Generated Mar 16, 2016 5:36:41 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.MapKeyJoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * OdsKrxMeta generated by hbm2java
 */
@Entity
@Table(name = "ods_krx_combo", catalog = "eugenefe")
public class OdsKrxCombo implements java.io.Serializable {
	private String isuCd;
	private String korIsuNm;
	
	public OdsKrxCombo() {
	}
	
	@Id
	@Column(name = "ISU_CD", unique = true, nullable = false)
	public String getIsuCd() {
		return isuCd;
	}
	public void setIsuCd(String isuCd) {
		this.isuCd = isuCd;
	}
	@Column(name = "KOR_ISU_NM", unique = true, nullable = false)
	public String getKorIsuNm() {
		return korIsuNm;
	}
	public void setKorIsuNm(String korIsuNm) {
		this.korIsuNm = korIsuNm;
	}
	
	
	
}
