package com.eugenefe.entity;
// Generated Mar 16, 2016 5:36:41 PM by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.MapKeyJoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OdsKrxMeta generated by hbm2java
 */
@Entity
@Table(name = "ods_krx_meta", catalog = "eugenefe")
public class OdsKrxMeta implements java.io.Serializable {

	private String metaId;
	private String viewNo;
	private String viewName;
	private String viewType;
	private String requestType;
	private String url;
	private String optUrl;
	private String filePath;
	private Map<String, String>  detail = new HashMap<String, String>();
//	private List<OdsKrxMetaDetail> odsKrxMetaDetails = new HashSet<OdsKrxMetaDetail>();
	private List<OdsKrxMetaDetail> odsKrxMetaDetails = new ArrayList<OdsKrxMetaDetail>();

	public OdsKrxMeta() {
	}

	public OdsKrxMeta(String metaId, String viewNo) {
		this.metaId = metaId;
		this.viewNo = viewNo;
	}

	public OdsKrxMeta(String metaId, String viewNo, String viewName, String viewType, String requestType, String url,
			String optUrl, List<OdsKrxMetaDetail> odsKrxMetaDetails) {
		this.metaId = metaId;
		this.viewNo = viewNo;
		this.viewName = viewName;
		this.viewType = viewType;
		this.requestType = requestType;
		this.url = url;
		this.optUrl = optUrl;
		this.odsKrxMetaDetails = odsKrxMetaDetails;
	}
	public OdsKrxMeta(String metaId, String viewNo, String viewName, String viewType, String requestType, String url,String optUrl) {
		this.metaId = metaId;
		this.viewNo = viewNo;
		this.viewName = viewName;
		this.viewType = viewType;
		this.requestType = requestType;
		this.url = url;
		this.optUrl = optUrl;
//		this.odsKrxMetaDetails = odsKrxMetaDetails;
	}
	@Id

	@Column(name = "META_ID", unique = true, nullable = false, length = 20)
	public String getMetaId() {
		return this.metaId;
	}

	public void setMetaId(String metaId) {
		this.metaId = metaId;
	}

	@Column(name = "VIEW_NO", nullable = false, length = 20)
	public String getViewNo() {
		return this.viewNo;
	}

	public void setViewNo(String viewNo) {
		this.viewNo = viewNo;
	}

	@Column(name = "VIEW_NAME", length = 50)
	public String getViewName() {
		return this.viewName;
	}

	public void setViewName(String viewName) {
		this.viewName = viewName;
	}

	@Column(name = "VIEW_TYPE", length = 10)
	public String getViewType() {
		return this.viewType;
	}

	public void setViewType(String viewType) {
		this.viewType = viewType;
	}

	@Column(name = "REQUEST_TYPE", length = 10)
	public String getRequestType() {
		return this.requestType;
	}

	public void setRequestType(String requestType) {
		this.requestType = requestType;
	}

	@Column(name = "URL", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "OPT_URL", length = 200)
	public String getOptUrl() {
		return this.optUrl;
	}

	public void setOptUrl(String optUrl) {
		this.optUrl = optUrl;
	}

	@Column(name = "FILE_PATH", length = 50)
	public String getFilePath() {
		return filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "odsKrxMeta")
	public List<OdsKrxMetaDetail> getOdsKrxMetaDetails() {
		return this.odsKrxMetaDetails;
	}

	public void setOdsKrxMetaDetails(List<OdsKrxMetaDetail> odsKrxMetaDetails) {
		this.odsKrxMetaDetails = odsKrxMetaDetails;
	}

//	@OneToMany(fetch = FetchType.LAZY)
////	@JoinTable(name ="ODS_KRX_META_DETAIL" , joinColumns
//	@JoinColumn(name ="META_ID")
//	@MapKeyJoinColumn(name ="MAP_KEY")
//	public Map<String, String> getDetail() {
//		return detail;
//	}
//
//	public void setDetail(Map<String, String> detail) {
//		this.detail = detail;
//	}
	
}
